"""Pinned-baseline review inventory, not exhaustive or verified coverage. Existing UI cards describe the inspected baseline only; they do not set current UX requirements. Follow docs/UI-UX-REDESIGN.md for accepted layout and behavior."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BOARDS = []


def board(key, group, title, files, symbols, tests, normal, adverse, acceptance,
          metric, related=(), requires=('fixture',)):
    BOARDS.append(dict(id=key, group=group, title=title,
                       sources=[str(ROOT / f) for f in files.split()],
                       symbols=symbols.split(), tests=tests.split(';'),
                       normal=normal.split('|'), adverse=adverse.split('|'),
                       cases=(normal + '|' + adverse).split('|'), acceptance=acceptance,
                       metric=metric, related=list(related), requires=list(requires)))


board('BOOT-01', 'Startup and lifecycle', 'Startup detection and GUI failure recovery',
      'src/main.rs src/tool_caps.rs docs/PROJECT-HISTORY.md',
      'try_run_gui detect_app_state build_native_options handle_gui_failure',
      'cargo test --lib tool_caps::tests -- --nocapture',
      'Healthy startup initializes one app|Missing feh produces actionable initial state',
      'Unavailable display/backend|Failed GUI fallback preserves an actionable error',
      'Startup and fallback do not silently succeed or lose required dependency warnings.',
      'Measure startup wall time and probe count separately from first-folder load.',
      ('CAP-01', 'PREF-01'), ('display', 'feh'))
board('BOOT-02', 'Startup and lifecycle', 'Startup folder and first-frame behavior',
      'src/main.rs docs/PROJECT-HISTORY.md docs/UI-UX-REDESIGN.md',
      'maybe_load_start_folder navigate_to_folder sync_auto_expand_folder_edge',
      'cargo test --test unit_ui_logic initial_open_sections -- --nocapture',
      'No folder starts with Browse available|Valid start folder is loaded once',
      'Missing or invalid start-folder path|First-frame scan must not fight user drawer state',
      'The startup hook is one-shot, invalid input is explained, and folder/scan state is consistent.',
      'Count startup scans and first-frame work; do not add repeated filesystem probes.',
      ('NAV-01', 'INSP-02'), ('display',))
board('LIFE-01', 'Startup and lifecycle', 'Shutdown and owned resource lifetime',
      'src/main.rs src/ui_logic.rs docs/PROJECT-HISTORY.md',
      'drop cancel_tools_job cleanup_prepare_fast_temp cleanup_stale_handoffs',
      'cargo test --lib cleanup_stale_handoffs -- --nocapture',
      'Idle close releases task-owned resources|Close after preparation cleans only owned files',
      'Close while batch/scan/decode is active|Viewer still using prepared files|Unrelated similarly named files',
      'No unrelated files/processes are removed; running readers and background writers have defined lifetime.',
      'Measure residual processes, temporary files and memory after repeated open/close cycles.',
      ('CACHE-05', 'VIEW-05'), ('display', 'feh'))
board('PREF-01', 'Preferences and persistence', 'Window size, lock and persistence',
      'src/main.rs src/ui_logic.rs src/types.rs tests/unit/ui_logic.rs docs/PROJECT-HISTORY.md',
      'load_window_prefs save_window_prefs apply_startup_window_prefs apply_window_resize_policy',
      'cargo test --test unit_ui_logic window_prefs -- --nocapture;cargo test --lib clamp_window_size -- --nocapture',
      'Preset persists across restart|Resizable and locked modes honor bounds',
      'Missing or corrupt JSON|Unwritable config directory|Small viewport or changed display scale',
      'Safe defaults and useful errors; runtime geometry matches persisted contract without resize loops.',
      'Count configuration writes and viewport commands during idle frames.',
      ('INSP-01', 'BOOT-01'), ('isolated-home', 'display'))
board('PREF-02', 'Preferences and persistence', 'Launch-entry persistence and identity',
      'src/ui_logic.rs src/types.rs src/main.rs tests/unit/ui_logic.rs docs/PROJECT-HISTORY.md',
      'save_launch_list load_launch_list persist_launch_entries FehLaunchList',
      'cargo test --test unit_ui_logic test_launch_list -- --nocapture',
      'Add/edit/remove entries then reload|Distinct IDs survive serialization',
      'Corrupt or missing file|Write failure|Labels and paths with Unicode',
      'Persistence neither drops unrelated entries nor confuses identity; failures do not masquerade as saved data.',
      'Measure writes per edit and reload time with many entries; no per-frame writes.',
      ('VIEW-02',), ('isolated-home',))
board('PREF-03', 'Preferences and persistence', 'Action destinations and safe configuration writes',
      'src/ui_logic.rs src/main.rs src/types.rs tests/unit/ui_logic.rs docs/PROJECT-HISTORY.md',
      'save_action_prefs_to load_action_prefs_from pick_action_destination ActionPrefs',
      'cargo test --lib action_prefs -- --nocapture',
      'Selected destination survives reload|Cancelled destination picker changes nothing',
      'Malformed or missing preferences|Interrupted/unwritable save|Destination disappears',
      'Preferences recover safely and cannot redirect actions silently to a stale or unintended location.',
      'Check write frequency and blocking filesystem work on action selection.',
      ('ACT-01', 'ACT-02'), ('isolated-home',))

board('SCAN-01', 'Discovery', 'Native classification without pixel decoding',
      'src/scanner.rs src/types.rs tests/feature_001_validation.rs docs/PROJECT-HISTORY.md',
      'is_native_image is_obvious_non_image classify_walk_file',
      'cargo test --lib scanner::tests -- --nocapture;cargo test --test feature_001_validation scan_10k_supported_files -- --nocapture',
      'Supported extensions and case variants|Empty directory and non-image files',
      'Misleading extension and corrupt bytes|Extensionless paths and unusual names',
      'Listing classification follows its extension contract without decoding full images or claiming decodability.',
      'Measure classification throughput on 1k and 10k metadata-only entries.', ('SCAN-04', 'STAGE-01'))
board('SCAN-02', 'Discovery', 'Traversal, recursion and filesystem boundaries',
      'src/scanner.rs tests/feature_001_validation.rs docs/PROJECT-HISTORY.md',
      'walk_scan_files scan_images scan_images_streaming',
      'cargo test --test feature_001_validation v5_recursive_scan_includes_subdirs -- --nocapture;cargo test --lib scanner::tests -- --nocapture',
      'Shallow scan excludes nested files|Recursive scan covers nested folders',
      'Symlink cycle and escape|Missing root and unreadable child|Root removed during traversal',
      'Traversal follows declared recursion/symlink policy and returns usable results with accurate warnings.',
      'Measure scaling with depth/file count and repeated metadata calls.', ('SCAN-03', 'SCAN-06'))
board('SCAN-03', 'Discovery', 'Warning classification and bounded summaries',
      'src/scanner.rs tests/feature_001_validation.rs docs/PROJECT-HISTORY.md',
      'format_walk_warning summarize_scan_warnings SCAN_WARNING_CAP',
      'cargo test --lib format_walk_warning -- --nocapture;cargo test --test feature_001_validation t068 -- --nocapture;cargo test --test feature_001_validation t069 -- --nocapture',
      'Permission warning preserves reason|Non-permission walk failure is visible',
      'More than warning cap|Repeated errors|Tests running with privileges that bypass permissions',
      'Warning count/omission summary is accurate; permission tests prove the error actually occurred.',
      'Measure warning allocation/log growth for error-heavy trees.', ('OBS-02',))
board('SCAN-04', 'Discovery', 'External format probing, budget and cancellation',
      'src/scanner.rs src/tool_caps.rs docs/PROJECT-HISTORY.md',
      'try_magick_probe is_magick_image MAGICK_IDENTIFY_CAP resolve_magick_bin',
      'cargo test --lib scanner::tests -- --nocapture',
      'Successful external classification|Disabled probe makes no subprocess calls',
      'All probes fail: attempted-call cap versus success count|Slow/hung probe during cancellation|Missing executable and adversarial path',
      'Record actual subprocess attempts, truncation and cancellation behavior; demonstrate any contract violation before fixing.',
      'Count launches and bound probe latency; inspect whether the cap applies to attempted or successful probes.',
      ('SCAN-06', 'CAP-02'), ('fake-executable', 'magick'))
board('SCAN-05', 'Discovery', 'Network-path policy and expensive metadata',
      'src/ui_logic.rs src/scanner.rs src/main.rs docs/PROJECT-HISTORY.md',
      'is_network_mount_path scan_magick_enabled scan_directory',
      'cargo test --lib network_mount_path -- --nocapture;cargo test --lib scan_magick_enabled -- --nocapture',
      'Recognized GVFS/SMB/NFS-like paths apply policy|Local path retains intended probe policy',
      'Unrecognized mount naming|Explicit format override|Slow directory metadata',
      'Policy and user-facing explanation agree; simulated path classification is not claimed as a real NAS test.',
      'Count metadata/probe work and record a real-network requirement separately from deterministic tests.',
      ('NAV-02', 'CAP-03'), ('fixture', 'network-optional'))
board('SCAN-06', 'Scan lifecycle', 'Superseded worker cancellation',
      'src/main.rs src/scanner.rs src/ui_logic.rs docs/PROJECT-HISTORY.md',
      'scan_directory walk_scan_files apply_converted_detection_cancellable',
      'cargo test --lib apply_converted_detection_cancellable -- --nocapture;cargo test --lib scanner::tests -- --nocapture',
      'New scan cancels prior walk|Pre-cancelled converted pass exits',
      'Rapid A-B-A navigation|Cancellation during external probe|Cancellation near completion',
      'Cancellation stops unnecessary work without suppressing the current scan; latency and limitations are evidenced.',
      'Measure cancellation-to-last-work latency and surviving thread/process count.', ('SCAN-04', 'SCAN-07'))
board('SCAN-07', 'Scan lifecycle', 'Partial/completion ordering and generation rejection',
      'src/main.rs docs/PROJECT-HISTORY.md docs/PROJECT-HISTORY.md',
      'apply_scan_partial handle_scan_msg poll_scan_complete ScanMsg',
      'cargo test --test feature_001_validation -- --nocapture',
      'Current partial followed by complete|Several partials coalesce to newest',
      'Old-generation partial/complete/converted events|Mixed queued generations|Completion then late event',
      'Deterministic event traces prove only valid updates apply and final list, inventory and scanning flag agree.',
      'Measure full-list copying/coalescing cost and backlog growth under fast producers.', ('SCAN-08', 'LIST-03'))
board('SCAN-08', 'Scan lifecycle', 'Converted merge and live inventory preservation',
      'src/main.rs src/ui_logic.rs src/types.rs docs/UI-UX-REDESIGN.md',
      'merge_converted_statuses handle_scan_msg ScanInventory',
      'cargo test --lib merge_converted -- --nocapture;cargo test --lib inventory_rebuilt_from_live_list -- --nocapture',
      'Matching path upgrades status|Unmatched live entry remains',
      'User add/move/rename before converted snapshot|Already-converted live state|Snapshot-only removed path',
      'No resurrection, lost mutation or downgrade; live inventory and revision invalidation reflect the merged list.',
      'Measure merge complexity and inventory rebuild at large counts.', ('ACT-02', 'BATCH-04', 'LIST-04'))

board('NAV-01', 'Folder navigation', 'Unified picker, Up and breadcrumb navigation',
      'src/main.rs docs/PROJECT-HISTORY.md',
      'navigate_to_folder pick_folder render_inspector_nav_strip',
      'cargo test --test unit_ui_logic list_subfolders -- --nocapture',
      'Picker/subfolder/Up use same navigation semantics|Root breadcrumb stops at filesystem root',
      'Picker cancel|Folder removed before navigation|Rapid successive requests',
      'All entry points set folder/search/selection consistently and do not cause duplicate scans.',
      'Measure navigation-to-first-result and redundant scan/subfolder requests.', ('BOOT-02', 'SCAN-06'), ('display',))
board('NAV-02', 'Folder navigation', 'Asynchronous subfolder discovery',
      'src/main.rs src/ui_logic.rs tests/unit/ui_logic.rs docs/PROJECT-HISTORY.md',
      'list_subfolders request_subfolders poll_subfolders SubfolderMsg',
      'cargo test --test unit_ui_logic list_subfolders -- --nocapture',
      'Sorted immediate directories only|Empty folder clears prior subfolder rows',
      'Late result from previous folder|Permission/missing root|Slow path with rapid navigation',
      'Stale generations cannot populate current navigation; pending state clears on all completion paths.',
      'Measure requests per navigation and ensure render does not rewalk folders.', ('SCAN-05', 'NAV-01'))
board('NAV-03', 'Folder navigation', 'Rescan selection and recursive-mode transitions',
      'src/main.rs docs/PROJECT-HISTORY.md docs/UI-UX-REDESIGN.md',
      'scan_directory apply_scan_result pending_select_path selected_tree_folder',
      'cargo test --test feature_001_validation v5_recursive_scan_includes_subdirs -- --nocapture',
      'Rescan current folder|Switch shallow to recursive and back',
      'Pending viewer landing during active scan|Selected file deleted|Old tree folder after folder change',
      'Selection uses documented precedence and never lands on an unrelated stale folder entry.',
      'Measure rescan work and time to stable selection.', ('VIEW-04', 'LIST-05'), ('display',))

board('LIST-01', 'List data and interaction', 'Path-aware search filtering',
      'src/ui_logic.rs src/main.rs tests/feature_001_validation.rs docs/PROJECT-HISTORY.md',
      'entry_matches_search filter_indices compute_list_indices',
      'cargo test --lib filter_ -- --nocapture;cargo test --test feature_001_validation sc003_filter_10k_under_200ms -- --nocapture',
      'Filename and relative-folder matches|Empty query and zero matches',
      'Mixed case and Unicode|Root changes with same query|Non-UTF8 filenames where supported',
      'Returned indices match the search contract and count; stale cached matches cannot leak across roots.',
      'Measure 1k/10k filtering separately from sorting and GUI frames.', ('LIST-03', 'LIST-05'))
board('LIST-02', 'List data and interaction', 'Sort order and viewer-filelist parity',
      'src/ui_logic.rs src/main.rs tests/feature_005_list.rs docs/PROJECT-HISTORY.md',
      'sort_key list_indices sort_mode_label write_feh_filelist',
      'cargo test --lib sort_by_ -- --nocapture;cargo test --lib feh_filelist_order -- --nocapture',
      'Path/name/folder sorts|Viewer order matches visible filtered order',
      'Identical names across folders|Ties and Unicode|Sort changed while selection persists',
      'Order is reproducible and each list index remains associated with its correct path.',
      'Measure sort-key allocations and sort time with duplicates and long paths.', ('VIEW-01', 'LIST-03'))
board('LIST-03', 'List data and interaction', 'Memoization and mutation invalidation',
      'src/main.rs src/ui_logic.rs docs/PROJECT-HISTORY.md',
      'compute_list_indices ListIndexKey TreeRowsKey images_revision',
      'cargo test --test feature_005_list -- --nocapture',
      'Repeated unchanged frames reuse data|Search/sort/root changes invalidate',
      'Rename/move/add/status changes|Revision wrapping|Cached vector clone cost',
      'Every mutation site is mapped to invalidation; cached and uncached reference results agree.',
      'Measure cache hit/miss calls and copied bytes at 1k/10k; optimization requires measured benefit.',
      ('SCAN-07', 'SCAN-08', 'BATCH-04'))
board('LIST-04', 'List data and interaction', 'Tree building, expansion and inventory counts',
      'src/ui_logic.rs src/types.rs src/main.rs tests/feature_005_list.rs docs/PROJECT-HISTORY.md',
      'build_folder_tree tree_visible_rows effective_expanded_paths ScanInventory',
      'cargo test --lib tree_ -- --nocapture;cargo test --lib inventory_ -- --nocapture',
      'Folder hierarchy and expansion|Filtered ancestors remain navigable',
      'Empty/deep tree|Converted and optimized entries|Updates after move or processed-add',
      'Visible rows, root counts and live inventory agree under filter and mutation sequences.',
      'Measure tree construction and flattening; verify work is not repeated every idle frame.', ('SCAN-08', 'LIST-03'))
board('LIST-05', 'List data and interaction', 'Selection, scrolling and row targeting',
      'src/main.rs docs/PROJECT-HISTORY.md docs/UI-UX-REDESIGN.md',
      'sync_selection_to_filter handle_image_row_click pending_flat_scroll_offset select_image',
      'cargo test --test feature_001_validation -- --nocapture',
      'Single click selects; explicit action opens|Sort/view toggle preserves intended selection',
      'Zero-match filter|Pending scroll target not yet present|Right-click unselected row|Moved selected item',
      'Actions target the clicked/selected contract and pending scroll is not consumed prematurely.',
      'Measure click-to-stage and scroll-to-target latency.', ('NAV-03', 'ACT-02', 'STAGE-02'), ('display',))
board('LIST-06', 'List data and interaction', 'Flat/tree virtualization and long-row layout',
      'src/main.rs src/ui_logic.rs docs/UI-UX-REDESIGN.md',
      'render_flat_image_list render_tree_image_list ImageListMetrics sections_drawer_reserved_height',
      'cargo test --lib sections_drawer -- --nocapture;cargo test --test feature_005_list -- --nocapture',
      '10k rows scroll with bounded rendering|Long paths truncate with complete hover text',
      'Drawer toggles during scroll|Very small/high-DPI window|Deep tree row-height drift',
      'Rendered rows and offsets stay consistent; accepted historical drift is measured rather than silently reopened.',
      'Measure frame latency/row count while scrolling, resizing and expanding drawer.', ('INSP-01', 'LIST-04'), ('display', 'input-control'))

board('INSP-01', 'Inspector', 'Inspector width and four-zone height budget',
      'src/main.rs src/ui_logic.rs docs/UI-UX-REDESIGN.md',
      'inspector_width inspector_max_width render_inspector_panel sections_drawer_body_height',
      'cargo test --lib sections_drawer -- --nocapture',
      'Persistent navigation/list with collapsed drawer|Expanded drawer remains bounded',
      'Narrow/short viewport|DPI change|Very long dynamic labels|No subfolders',
      'Height remains bounded and width reclamps on resize; no unbounded outer scrolling breaks virtualization.',
      'Measure layout recalculation, font-measure calls and resize jitter.', ('LIST-06', 'PREF-01'), ('display',))
board('INSP-02', 'Inspector', 'Drawer auto-expand state machine',
      'src/ui_logic.rs src/main.rs tests/unit/ui_logic.rs docs/UI-UX-REDESIGN.md',
      'AutoExpandState sync_auto_expand_folder_edge toggle_inspector_section',
      'cargo test --lib auto_expand -- --nocapture;cargo test --test unit_ui_logic initial_open_sections -- --nocapture',
      'Rising edge opens once; falling edge retracts machine-owned sections|User-open section survives retraction',
      'User closes during scan|Overlapping no-folder/scan/missing-tool triggers|Recheck while manually open',
      'All trigger/user transitions have asserted ownership and suppression behavior; no per-frame reopening.',
      'Count state transitions and repaints rather than assuming animation cost.', ('CAP-01', 'BOOT-02'))
board('INSP-03', 'Inspector', 'Section detach and reattach lifecycle',
      'src/main.rs src/ui_logic.rs src/types.rs docs/UI-UX-REDESIGN.md',
      'render_detached_inspector_windows detached_window_chrome InspectorSection DetachedWindow',
      'cargo test --test unit_ui_logic initial_open_sections -- --nocapture',
      'Each of seven sections detaches/docks|Detached body matches docked controls',
      'Multiple sections open|Close detached window then reopen|Resize and changed selection',
      'Deterministic IDs/order, no duplicate control owner, and closing does not lose unrelated section state.',
      'Measure idle repaint and duplicate rendering with several detached sections.', ('INSP-04', 'OBS-01'), ('display', 'input-control'))
board('INSP-04', 'Inspector', 'Pinned image context and safe action scope',
      'src/main.rs src/ui_logic.rs tests/unit/ui_logic.rs docs/UI-UX-REDESIGN.md',
      'panel_context render_image_actions_pin_toggle pinned_path_in_filtered_list open_in_feh_pinned',
      'cargo test --test unit_ui_logic panel_context -- --nocapture',
      'Pin remains on image while live selection changes|Unpin follows live selection',
      'Pinned file disappears or belongs to another folder|Batch tabs while pinned|Viewer close changes live selection',
      'Every enabled action acts on documented context; folder-scoped actions cannot silently target a different folder.',
      'Check pinned validation for per-frame filesystem work and filter membership cost.', ('VIEW-04', 'ACT-01', 'BATCH-01'), ('display',))

board('STAGE-01', 'Selected-image stage', 'Decode, dimension bounds and aspect correctness',
      'src/image_proc.rs src/ui_logic.rs src/types.rs tests/unit/image_proc.rs docs/PROJECT-HISTORY.md',
      'decode_stage_rgba stage_decode_bounds StagedImage',
      'cargo test --lib decode_stage_rgba -- --nocapture;cargo test --lib stage_decode_bounds -- --nocapture',
      'Landscape/portrait/small images fit within bounds|Real JPEG/PNG/WebP images decode',
      'Zero/huge dimensions|Corrupt/missing source|Exotic format without decoder',
      'Returned dimensions/buffer size/aspect are valid and unsupported input is explicit; uncommitted aspect_ratio helper is not assumed in baseline.',
      'Measure decode wall time and peak allocation with real images, not fake JPEG names.', ('STAGE-02', 'IMAGE-01'))
board('STAGE-02', 'Selected-image stage', 'Decode supersession and texture lifecycle',
      'src/main.rs src/types.rs docs/PROJECT-HISTORY.md',
      'kick_stage_decode_if_selection_changed poll_stage_decode StageDecodeMsg render_stage_image',
      'cargo test --lib decode_stage_rgba -- --nocapture',
      'Selected image appears after decode|Unchanged selection avoids repeated decode',
      'Rapid A-B-A selection with reordered completion|Error after newer success|Folder change or moved file during decode',
      'Old completions cannot replace current stage; textures and worker state have bounded lifetime.',
      'Measure input-to-visible-image latency and retained texture/memory across repeated selection.',
      ('LIST-05', 'LIFE-01'), ('display',))
board('STAGE-03', 'Selected-image stage', 'Stage empty/error state and action gating',
      'src/main.rs src/ui_logic.rs docs/PROJECT-HISTORY.md',
      'render_stage_pane render_stage_status_line render_image_context_menu file_status_decodable',
      'cargo test --lib file_status_decodable -- --nocapture',
      'No selection shows intentional empty state|Stage remains image-only with status outside image',
      'Undecodable or deleted file|Context menu during pending decode|Unsupported processing action',
      'Status and action availability agree with actual selection/decodability without stale-image actions.',
      'Measure idle repaints and repeated error/decode retries.', ('ACT-04', 'OBS-01'), ('display', 'input-control'))

board('VIEW-01', 'Viewer integration', 'Filelist, spawn arguments and isolated profile',
      'src/ui_logic.rs src/main.rs tests/integration/feature_016_roundtrip.rs docs/PROJECT-HISTORY.md docs/PROJECT-HISTORY.md',
      'viewer_spawn_command write_feh_filelist open_in_feh viewer_profile_dir',
      'cargo test --lib viewer_spawn_command -- --nocapture;cargo test --lib write_feh_filelist -- --nocapture',
      'Filtered sorted list starts at selected path|Geometry and viewer-profile isolation',
      'Spaces/quotes/Unicode/newline-like path boundaries|Empty list|Spawn permission failure',
      'Argument vector and handoff quoting are safe, list encoding limitations explicit, and personal feh profile unchanged.',
      'Measure filelist creation and launch-to-first-image separately.', ('LIST-02', 'CAP-01'), ('feh', 'display', 'isolated-home'))
board('VIEW-02', 'Viewer integration', 'Launch entries, folders and multiple viewers',
      'src/main.rs src/ui_logic.rs tests/unit/ui_logic.rs tests/integration/feature_014_folders.rs docs/PROJECT-HISTORY.md',
      'build_entry_filelist entry_is_launchable launch_entry_feh launch_all_entries',
      'cargo test --test unit_ui_logic test_entry -- --nocapture;cargo test --test feature_014_folders -- --list',
      'Entry launches its own assigned folder|Launch all handles several entries independently',
      'Unassigned/missing/empty folder|Entry folder differs from current browse folder|Tool disappears before launch',
      'No dependence on current flat list; per-entry success/failure is accurate and does not suppress other entries.',
      'Count per-frame folder stats and launch-time scans; count-cache deferral is not new-feature authorization.',
      ('PREF-02', 'CAP-01'), ('feh', 'display', 'fixture-folders'))
board('VIEW-03', 'Viewer integration', 'Handoff validation and deleted-image fallback',
      'src/ui_logic.rs tests/integration/feature_016_roundtrip.rs docs/PROJECT-HISTORY.md',
      'validate_handoff matching_filelist_index nearest_surviving_neighbor handoff_path',
      'cargo test --lib validate_handoff -- --nocapture;cargo test --test feature_016_roundtrip -- --nocapture',
      'Exact trusted filelist image resolves|Unchanged handoff preserves selection',
      'Tampered/empty/garbage content|Symlink escape|Landed file deleted|Distinct viewers have distinct files',
      'Only trusted surviving entries are accepted; rejected content cannot cause arbitrary file operations.',
      'Measure validation work with large filelists and expensive canonicalization.', ('VIEW-04', 'VIEW-05'), ('isolated-home',))
board('VIEW-04', 'Viewer integration', 'Return selection, cross-folder landing and exit order',
      'src/main.rs docs/PROJECT-HISTORY.md docs/PROJECT-HISTORY.md',
      'poll_round_trip_viewers handle_round_trip_exit stage_selection_from_round_trip',
      'cargo test --test feature_016_roundtrip -- --nocapture',
      'Navigate in viewer then close and stage landed image|Cross-folder return navigates before selecting',
      'Return during rescan|Two viewers exit in reversed order|Pinned context vs live selection|Landed file deleted',
      'Exact GUI landing/scroll/stage behavior is demonstrated, not inferred from protocol-only tests.',
      'Measure close-to-correct-stage latency and redundant rescans.', ('NAV-03', 'LIST-05', 'INSP-04'), ('feh', 'display', 'input-control'))
board('VIEW-05', 'Viewer integration', 'Viewer child ownership and handoff cleanup',
      'src/main.rs src/ui_logic.rs tests/integration/feature_016_roundtrip.rs docs/PROJECT-HISTORY.md',
      'spawn_round_trip_viewer poll_round_trip_viewers cleanup_stale_handoffs ViewerRoundTrip',
      'cargo test --lib cleanup_stale_handoffs -- --nocapture;cargo test --test feature_016_roundtrip handoff_path -- --nocapture',
      'Normal viewer exit cleans its handoff|Independent viewers remain isolated',
      'Abnormal child exit|App restart with stale handoff|Concurrent app processes|PID/name collision',
      'Cleanup does not remove a live peer session or unrelated file; child exit is observed without blocking UI.',
      'Measure poll cost and stale-file accumulation over repeated viewer sessions.', ('LIFE-01', 'CACHE-05'), ('feh', 'isolated-home'))

board('ACT-01', 'File actions and clipboard', 'Save-copy destination and collision safety',
      'src/ui_logic.rs src/main.rs tests/integration/feature_016_actions.rs docs/PROJECT-HISTORY.md',
      'save_copy_to collision_suffixed_path action_save_copy',
      'cargo test --lib save_copy_to -- --nocapture;cargo test --lib collision_suffixed_path -- --nocapture',
      'Copy into new destination|Existing filename selects safe alternate',
      'Read-only destination|Source equals destination|Symlink destination or concurrent collision|Unicode/dotfiles',
      'Original bytes remain unchanged; existing unrelated destinations are not clobbered; failure leaves a defined state.',
      'Measure copy overhead without treating safety checks as optional.', ('PREF-03', 'ACT-03'))
board('ACT-02', 'File actions and clipboard', 'Loss-proof moves and post-move selection',
      'src/ui_logic.rs src/main.rs tests/integration/feature_016_actions.rs docs/PROJECT-HISTORY.md',
      'plan_loss_proof_move execute_move_plan action_move_to advance_stage_after_move',
      'cargo test --lib loss_proof_move -- --nocapture;cargo test --test feature_016_actions -- --nocapture',
      'Same-filesystem move|Selected versus unselected source move updates correct row',
      'Cross-filesystem fallback|Copy verification or deletion fails|Destination race|User move while converted refresh arrives',
      'Source is removed only after verified success; partial outcomes are explicit; unrelated selection is not hijacked.',
      'Measure filesystem branches separately; do not optimize away preservation checks.',
      ('SCAN-08', 'LIST-05', 'ACT-03'), ('fixture', 'cross-filesystem-optional'))
board('ACT-03', 'File actions and clipboard', 'Output policies, backups and write boundaries',
      'src/image_proc.rs src/ui_logic.rs src/types.rs tests/unit/ui_logic.rs docs/PROJECT-HISTORY.md',
      'compute_output_path create_backup policy_requires_backup OutputPolicy',
      'cargo test --test unit_ui_logic compute_output_path -- --nocapture;cargo test --test integration_image_tools sc005 -- --nocapture',
      'Subfolder/suffix outputs preserve originals|In-place mode creates promised backup',
      'Existing backup|Traversal/absolute output components|Disk-full or interrupted write|Cache-hit bypass path',
      'Each policy has explicit overwrite/backup/partial-write semantics and cannot silently violate original preservation.',
      'Measure backup/write overhead separately from transforms; safety behavior is invariant.', ('CACHE-03', 'IMAGE-03'))
board('ACT-04', 'File actions and clipboard', 'Context-menu action dispatch and outcomes',
      'src/main.rs src/ui_logic.rs docs/PROJECT-HISTORY.md docs/UI-UX-REDESIGN.md',
      'render_image_context_menu run_derived_action record_action_outcome format_action_outcome',
      'cargo test --lib format_action_outcome -- --nocapture;cargo test --lib file_status_decodable -- --nocapture',
      'Stage/flat/tree context menus dispatch same behavior|Cancel is not success or failure',
      'Right-click non-selected image|Operation fails after source changes|Pinned image context',
      'Target, produced path, error and inventory effects are consistent across every action entry point.',
      'Measure synchronous action blocking and outcome-to-visible-state delay.', ('INSP-04', 'OBS-01'), ('display', 'input-control'))
board('CLIP-01', 'File actions and clipboard', 'Copy path, pixels and clipboard availability',
      'src/ui_logic.rs src/main.rs tests/integration/clipboard_copy.rs docs/PROJECT-HISTORY.md',
      'copy_image_to_clipboard decode_image_to_rgba action_copy_image',
      'cargo test --test unit_ui_logic test_clipboard -- --nocapture;cargo test --test integration_clipboard_copy -- --list',
      'Copied path is exact|RGBA bytes/dimensions round-trip through isolated clipboard',
      'No backend/readback|Missing/corrupt/large image|Clipboard owner lifetime after function return',
      'Report actual execution separately from skip; no personal clipboard contents are overwritten during review.',
      'Measure decode/clipboard blocking and peak memory with representative real images.',
      ('STAGE-01', 'OBS-02'), ('isolated-clipboard', 'display'))

board('IMAGE-01', 'Image transformations', 'Resize dimensions, fit and filter semantics',
      'src/image_proc.rs src/main.rs src/types.rs tests/unit/image_proc.rs docs/PROJECT-HISTORY.md',
      'process_image process_image_crate tools_build_resize_op Filter FitMode',
      'cargo test --test unit_image_proc -- --nocapture;cargo test --test integration_image_tools single_resize -- --nocapture',
      'Width/height/percentage controls|Fit and filter selection match output geometry',
      'Zero/negative/nonfinite input|Extreme aspect or dimensions|External versus native route',
      'Decoded output dimensions and aspect match chosen semantics; invalid input cannot produce destructive output.',
      'Measure decode/resize/encode phases and memory with identical images and build mode.', ('ACT-03', 'IMAGE-03'))
board('IMAGE-02', 'Image transformations', 'Crop parsing, clamping and preview parity',
      'src/image_proc.rs src/ui_logic.rs src/main.rs tests/unit/image_proc.rs tests/unit/ui_logic.rs docs/PROJECT-HISTORY.md',
      'parse_crop_geometry clamp_crop crop_image crop_preview_pixels render_tools_crop_preview',
      'cargo test --test unit_image_proc parse_crop -- --nocapture;cargo test --test unit_ui_logic crop_preview -- --nocapture',
      'Valid positive geometry|Preview pixels and saved crop agree',
      'Negative offsets|Out-of-bounds/zero/overflow geometry|Selection changes while preview cached',
      'Parsing and preview use the same coordinate semantics; invalid crops preserve original and show reason.',
      'Measure preview regeneration frequency and crop latency.', ('STAGE-02', 'ACT-03'))
board('IMAGE-03', 'Image transformations', 'Encoding, conversion and external fallback',
      'src/image_proc.rs src/tool_caps.rs tests/integration/image_tools.rs docs/PROJECT-HISTORY.md',
      'write_image execute_op_to_path run_magick_resize_convert run_magick_crop',
      'cargo test --test integration_image_tools -- --list;cargo test --test unit_image_proc -- --nocapture',
      'Supported output formats decode correctly|Quality/filter choices reach intended backend',
      'Alpha-to-JPEG|Missing or failing magick|Extension differs from encoded format|Unsupported requested format',
      'Output bytes, format, dimensions and reported destination agree; backend failure is explicit and preserves input.',
      'Measure each backend separately and report optional-tool coverage honestly.',
      ('CAP-02', 'ACT-03', 'CACHE-02'), ('magick', 'fake-executable'))

board('BATCH-01', 'Batch and rename', 'Batch target snapshot, progress and cancellation',
      'src/main.rs src/image_proc.rs docs/PROJECT-HISTORY.md',
      'tools_batch_paths tools_start_batch_job cancel_tools_job poll_batch_job_rx process_batch',
      'cargo test --test integration_image_tools batch_mixed_success_and_failure -- --nocapture',
      'Batch uses documented filtered target set|Progress accounts for every input',
      'Filter/folder changes after start|Cancel mid-item|Mixed failures and missing sources|Pinned context',
      'Input snapshot is explicit; cancellation and summary account for completed/failed/skipped work without corrupting outputs.',
      'Measure progress cadence, cancellation latency and UI blocking.', ('INSP-04', 'BATCH-04'), ('fixture', 'display'))
board('BATCH-02', 'Batch and rename', 'Rename token expansion and collision preview',
      'src/ui_logic.rs src/main.rs tests/unit/ui_logic.rs docs/PROJECT-HISTORY.md',
      'expand_rename_pattern expand_one_rename_token replace_counter tools_refresh_rename_preview',
      'cargo test --test unit_ui_logic expand_rename -- --nocapture;cargo test --test perf_sc_timing sc007 -- --nocapture',
      'Original/ext/counter/date tokens|Deterministic input order and counter padding',
      'Duplicate target names|Existing file collision|Traversal or malformed token|Counter boundary/date rollover',
      'Preview rejects invalid/colliding plans before writes and matches exact eventual target names.',
      'Measure preview for 500 and larger lists without a per-frame filesystem scan.', ('BATCH-03',))
board('BATCH-03', 'Batch and rename', 'Rename execution and rollback safety',
      'src/ui_logic.rs src/main.rs tests/integration/image_tools.rs docs/PROJECT-HISTORY.md',
      'apply_rename_pairs tools_apply_rename RenameApplyOutcome',
      'cargo test --test integration_image_tools rename_apply_rolls_back -- --nocapture',
      'Successful multi-file rename|Inventory names update after success',
      'Failure partway through plan|Rollback itself fails|Name swap/cycle|Target appears after preview',
      'No unrelated file loss; partial and rollback outcomes identify exact remaining filesystem state.',
      'Measure rename/rollback work separately; collision prevention must remain intact.', ('BATCH-02', 'BATCH-04'))
board('BATCH-04', 'Batch and rename', 'Processed assets, summaries and inventory integration',
      'src/ui_logic.rs src/main.rs src/types.rs tests/unit/ui_logic.rs docs/PROJECT-HISTORY.md',
      'add_or_update_asset_in_inventory refresh_entry_and_inventory aggregate_batch_results tools_on_processed',
      'cargo test --test unit_ui_logic aggregate_batch_results_counts -- --nocapture;cargo test --test unit_ui_logic inventory_add_processed -- --nocapture',
      'New outputs appear once|Summary matches actual successes/failures',
      'Existing output path reused|Folder changed during job|Converted snapshot arrives late|Cancellation leaves partial assets',
      'List, inventory, status and cache invalidation describe actual produced assets without duplication or lost user changes.',
      'Measure per-output versus batch refresh costs and redundant rebuilds.', ('SCAN-08', 'LIST-03', 'CACHE-05'))

board('CACHE-01', 'Cache and prepared viewing', 'Cache readiness, configuration and disabled mode',
      'src/image_proc.rs src/main.rs src/types.rs tests/unit/image_proc.rs docs/MAGICK-CACHE-SETUP.md',
      'cache_ready cache_probe cache_root_path update_cache render_tools_cache_config',
      'cargo test --test unit_image_proc -- --nocapture;cargo test --test integration_image_tools cache_repeat -- --list',
      'Disabled mode avoids cache subprocesses|Valid isolated cache config becomes ready',
      'Missing binary/passkey/root|Unwritable root|Readiness changes during operation',
      'Cache remains optional; readiness errors do not disable native tools or expose secrets.',
      'Measure readiness probe frequency and avoid expensive checks on each frame.',
      ('CAP-01', 'CACHE-02'), ('isolated-cache', 'magick-cache'))
board('CACHE-02', 'Cache and prepared viewing', 'Cache identity, freshness and hit/miss correctness',
      'src/image_proc.rs tests/unit/image_proc.rs tests/integration/image_tools.rs docs/PROJECT-HISTORY.md',
      'make_iri op_params_key process_single cache_put cache_get',
      'cargo test --test unit_image_proc -- --nocapture;cargo test --test integration_image_tools cache_repeat -- --list',
      'Same source/parameters may hit|Changed operation parameters must not share result',
      'Source bytes replaced at same path|Path normalization/collision|Corrupt cached output|TTL expiry',
      'A hit returns output equivalent to fresh processing of the intended source and parameters; actual hit is asserted.',
      'Compare cold/warm runs with asserted hits and identical output validation, not only elapsed time.',
      ('IMAGE-03', 'CACHE-03'), ('isolated-cache', 'magick-cache'))
board('CACHE-03', 'Cache and prepared viewing', 'Cache-hit output policy and backup preservation',
      'src/image_proc.rs src/ui_logic.rs docs/PROJECT-HISTORY.md',
      'process_single create_backup compute_output_path',
      'cargo test --test integration_image_tools sc005 -- --nocapture;cargo test --test integration_image_tools cache_repeat -- --list',
      'Cache hit under safe new-file policy|Cache miss under in-place-with-backup policy',
      'Cache hit with in-place policy returns before backup branch|Cache export fails partway|Existing backup',
      'Controlled hit/miss reproductions establish backup and original-preservation behavior; suspicion alone is not a confirmed defect.',
      'Measure only after safety parity is proven; no speed target can bypass backup.',
      ('ACT-03', 'CACHE-02'), ('isolated-cache', 'magick-cache', 'fake-executable'))
board('CACHE-04', 'Cache and prepared viewing', 'Precache jobs, progress and cancellation',
      'src/image_proc.rs src/main.rs docs/PROJECT-HISTORY.md',
      'pre_cache_one pre_cache_paths tools_start_precache_job poll_precache_job_rx',
      'cargo test --test integration_image_tools -- --list',
      'Precache snapshot completes with accurate count|Browsing stays responsive',
      'Cache unavailable mid-job|Cancel with pending write|Folder changes|Mixed inaccessible files',
      'Job terminates with accurate successful/failed/skipped accounting and does not modify originals.',
      'Measure per-image overhead, progress cadence and cancellation latency.',
      ('BATCH-01', 'CACHE-01'), ('isolated-cache', 'magick-cache', 'display'))
board('CACHE-05', 'Cache and prepared viewing', 'Prepare-fast materialization, launch and cleanup',
      'src/image_proc.rs src/main.rs src/ui_logic.rs docs/PROJECT-HISTORY.md',
      'prepare_fast_one prepare_fast_set tools_finish_prepare_fast open_feh_on_prepared_fast',
      'cargo test --test integration_image_tools prepare_fast_set -- --nocapture;cargo test --test perf_sc_timing sc004 -- --nocapture',
      'Real optimized files are usable and listed|Viewer receives materialized paths',
      'Partial prepare/cancel|Repeated prepare while viewer uses old files|Same filename from different folders|Shutdown during job',
      'Materialized outputs have unique correct identity and remain alive while consumers need them; originals unchanged.',
      'Compare preparation plus first/subsequent view latency with raw path; report breakeven and peak disk/memory.',
      ('LIFE-01', 'VIEW-05', 'BATCH-04'), ('magick', 'feh', 'display'))

board('CAP-01', 'Capabilities and feedback', 'Tool detection, recheck and mid-session loss',
      'src/tool_caps.rs src/main.rs docs/PROJECT-HISTORY.md',
      'detect refresh_tool_caps mark_feh_unavailable feh_spawn_unavailable',
      'cargo test --lib tool_caps::tests -- --nocapture',
      'Tool absent then present after recheck|Healthy recheck restores controls',
      'Tool removed between detection and spawn|Permission denied vs genuinely missing|Different PATH per task',
      'Capabilities and controls reflect actual conditions; arbitrary spawn failures are not mislabeled as missing tools.',
      'Measure detection process count and latency; no repeated full detection on idle frames.',
      ('INSP-02', 'VIEW-01'), ('fake-executable',))
board('CAP-02', 'Capabilities and feedback', 'Format routes and advertised processing capability',
      'src/tool_caps.rs src/image_proc.rs src/scanner.rs docs/PROJECT-HISTORY.md docs/PROJECT-HISTORY.md',
      'format_routes Handler SpeedTier has_external_magick',
      'cargo test --lib format_routes -- --nocapture',
      'Common-format native route|Optional exotic route with external tool',
      'Listed-but-not-decodable formats|magick versus convert availability|Documentation claims without reachable implementation',
      'Discovery, stage decoding, processing and viewer support are distinguished accurately; unsupported claims become documentation findings.',
      'Measure capability-render overhead and ensure route hints are not mistaken for benchmarks.', ('SCAN-04', 'IMAGE-03'))
board('CAP-03', 'Capabilities and feedback', 'Dependency guidance and format UI',
      'src/main.rs src/tool_caps.rs docs/PROJECT-HISTORY.md docs/PROJECT-HISTORY.md',
      'render_dependency_row render_format_discovery_body dependencies operation_timings',
      'cargo test --lib dependencies_ -- --nocapture;cargo test --lib operation_timings -- --nocapture',
      'Missing required tool exposes guidance|Install/copy/recheck controls discoverable',
      'Optional tool missing does not block core workflow|Long hints and detached section|Network probe disabled reason',
      'Hints, required/optional distinctions and enabled actions agree with runtime capability snapshot.',
      'Measure expensive checks during rendering and duplicate guidance updates.', ('CAP-01', 'INSP-03'), ('display',))
board('OBS-01', 'Capabilities and feedback', 'Progress, status precedence and busy repaint',
      'src/main.rs src/ui_logic.rs docs/PROJECT-HISTORY.md',
      'is_activity_busy request_repaint_if_busy post_scan_status render_session_status_body',
      'cargo test --lib post_scan_ -- --nocapture;cargo test --test feature_001_validation v3_status -- --nocapture',
      'Scan/job progress appears and clears|Required dependency warning survives successful load',
      'Concurrent scan and job|Error followed by unrelated success|Cancelled job leaves spinner|Idle redraw loop',
      'Status does not report stale success or permanent busy state; important errors remain actionable.',
      'Measure idle/busy CPU, repaint cadence and status latency.', ('INSP-02', 'BATCH-01'), ('display',))
board('OBS-02', 'Capabilities and feedback', 'Activity log retention, copy and error fidelity',
      'src/main.rs src/ui_logic.rs docs/PROJECT-HISTORY.md',
      'log join_activity_log render_activity_log_body status_text_for_copy',
      'cargo test --lib join_activity_log -- --nocapture;cargo test --lib format_action_outcome -- --nocapture',
      'Actions and warnings preserve paths/reasons|Copy log/status matches visible source',
      'More than retention cap|Multiline/Unicode paths|Detached log|Sensitive tool arguments',
      'Log stays bounded and useful without leaking secrets; copy checks run only with isolated clipboard.',
      'Measure log churn and repeated joining cost under scan-warning load.', ('CLIP-01', 'SCAN-03'), ('display', 'isolated-clipboard'))

board('VERIFY-01', 'Verification infrastructure', 'Test isolation, fixtures and honest skip accounting',
      'tests/unit/ui_logic.rs tests/integration/desktop_tools_variations.rs tests/integration/clipboard_copy.rs tests/integration/image_tools.rs Cargo.toml',
      'HOME_LOCK skip_unless_fixtures display_available',
      'cargo test -- --list',
      'Every selected test is enumerated|Synthetic folders enable tests without personal libraries',
      'Early returns appear as passes|Concurrent HOME mutation|Real cache/clipboard side effects|Zero tests matched',
      'Produce executed/skipped/blocked inventory and an isolation recipe; do not run unsafe suites until prerequisites are satisfied.',
      'Measure suite duration and flakiness by repeated isolated runs, not static test counts.', ('VERIFY-02', 'CLIP-01'))
board('VERIFY-02', 'Verification infrastructure', 'Benchmark fixtures, provenance and process ownership',
      'tests/perf/sc_timing.rs scripts/generate-perf-fixture.sh scripts/measure-resources.sh scripts/sample-rss.sh',
      'sc002_cache_disabled_repeat_similar_timing sc004_prepare_fast_batch_under_60s',
      'cargo test --test perf_sc_timing -- --list',
      'Metadata and real-image fixtures are separate|Measured binary matches recorded candidate',
      'Nonzero duration mistaken for similar timing|Stale root binary|Global pkill|Peak sampling misses high-water mark',
      'Define reproducible meaningful metrics and safe owned-PID capture; legacy scripts are reviewed before any execution.',
      'Report repeated median/spread, build mode, hardware and cold/warm state; no invented universal speedup threshold.', ('VERIFY-01',))
board('VERIFY-03', 'Verification infrastructure', 'Build, CI and packaging verification',
      '.github/workflows/ci.yml Cargo.toml Cargo.lock build-and-place.sh README.md',
      'profile.release',
      'cargo test -- --list;cargo fmt --check;cargo clippy --all-targets -- -D warnings;cargo build --release',
      'Document exact current CI gates|Release binary and launcher use current build',
      'Existing fmt/clippy drift|Missing optional runtime tools|Build script wrong cwd/shell|Untracked changes absent from baseline',
      'Separate baseline failures from regressions; no unrelated formatting rewrite or dependency upgrades to make gates appear green.',
      'Measure build/release size only on matching revision/profile and report reproducibility limits.', ('VERIFY-01',))
board('VERIFY-04', 'Verification infrastructure', 'Requirement and source coverage reconciliation',
      'README.md docs/PROJECT-HISTORY.md .agents/BACKLOG.md .agents/BOARD.md .specify/feature.json src/lib.rs',
      'scanner image_proc tool_caps types ui_logic',
      'git ls-files;cargo test -- --list',
      'Each active entry point/helper has one primary board|Specs 002/004 map to successor behavior',
      'README wallpaper claim lacks reachable spawn|Deferred 015 treated as shipped|Historical completed status conflicts with evidence|Unmapped public helper',
      'Publish an auditable source-to-board/requirement/test matrix; uncovered code is explicitly assigned or excluded with reason, never silently ignored.',
      'This is coverage reconciliation, not a performance task; count uncovered behaviors rather than lines alone.', ('CAP-02', 'VERIFY-01'))


def manifest(baseline):
    return dict(baseline=baseline, project=str(ROOT),
                workspace_root='/home/kkk/.cline/kanban-review-workspaces/rust-feh',
                boards=BOARDS)
